import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col gap-2">
        <nav className="flex justify-between p-2">
            <div className="p-6 flex gap-1 items-center text-blue-600">
        <h1 className="font-bold text-xl">GOUNI</h1>
        <p className="text-slate-400 ">
          Admissions Dashboard
        </p>
      </div>


        </nav>
        {children}
        </body>
    </html>
  );
}
